# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  enabled: true
  # host: localhost
  # port: 8080
  host: dev-quiz-anvkos.c9users.io
  port: 8081

development:
  <<: *default

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
